/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chaturanga;

/**
 *
 * @author Frances
 */
public class CrearPlayer extends javax.swing.JFrame {

    /**
     * Creates new form CrearPlayer
     */
    Usuarios users= new Usuarios();
    public CrearPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcplayernombre = new javax.swing.JTextField();
        btncplayerguardar = new javax.swing.JButton();
        btncplayercancelar = new javax.swing.JButton();
        txtcplayercontraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 230, 93, 22);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 300, 110, 22);

        txtcplayernombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcplayernombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtcplayernombre);
        txtcplayernombre.setBounds(300, 220, 181, 30);

        btncplayerguardar.setBackground(new java.awt.Color(0, 0, 0));
        btncplayerguardar.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        btncplayerguardar.setForeground(new java.awt.Color(255, 255, 255));
        btncplayerguardar.setText("CREAR");
        btncplayerguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncplayerguardarMouseClicked(evt);
            }
        });
        btncplayerguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncplayerguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btncplayerguardar);
        btncplayerguardar.setBounds(250, 440, 160, 33);

        btncplayercancelar.setBackground(new java.awt.Color(0, 0, 0));
        btncplayercancelar.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        btncplayercancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncplayercancelar.setText("CANCELAR");
        btncplayercancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncplayercancelarMouseClicked(evt);
            }
        });
        btncplayercancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncplayercancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncplayercancelar);
        btncplayercancelar.setBounds(470, 440, 150, 33);
        getContentPane().add(txtcplayercontraseña);
        txtcplayercontraseña.setBounds(300, 290, 181, 30);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 3, 24)); // NOI18N
        jLabel3.setText("CREAR NUEVO USUARIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 100, 360, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-7, -1, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncplayerguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncplayerguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncplayerguardarActionPerformed

    private void txtcplayernombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcplayernombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcplayernombreActionPerformed

    private void btncplayercancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncplayercancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncplayercancelarActionPerformed

    private void btncplayerguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncplayerguardarMouseClicked
        // TODO add your handling code here:
        String nombre=txtcplayernombre.getText();
        char[] contra=txtcplayercontraseña.getPassword();
        
        if(nombre.equalsIgnoreCase(""))
            System.out.println("Debe Ingresar un Nombre de Usuario");
        else{
        if(users.buscar(txtcplayernombre.getText())==null){
            if(contra.length==5){
                users.players.add(new Usuario(nombre,contra));
            }
            else{
                System.out.println("la contraseña debe ser de 5 caracteres");
            }
        }
        else
            System.out.println("el nombre ingresado ya existe");
        }
    }//GEN-LAST:event_btncplayerguardarMouseClicked

    private void btncplayercancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncplayercancelarMouseClicked
        // TODO add your handling code here:
        
        txtcplayernombre.setText("");
        txtcplayercontraseña.setText("");
        
    }//GEN-LAST:event_btncplayercancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPlayer().setVisible(true);
            }
        });
        
        //txtcplayercontraseña
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncplayercancelar;
    private javax.swing.JButton btncplayerguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtcplayercontraseña;
    private javax.swing.JTextField txtcplayernombre;
    // End of variables declaration//GEN-END:variables
}
